C_class: 1000000.0
C_quant: 1000000.0
add_to_tracklet: null
alpha: 0.1
circuit_width: 9
class_weight:
  0: 1.0
  1: 1.0
classical: false
data_scaler: inner_global
division: new_phi
gamma: 1
interaction: YY
load_model: false
model_file: null
num_test: 20
num_train: 10
pair_mapping: 1
region_id: '14'
single_mapping: 1
tracklet_dataset: inner_triplet
