C_class: 1000000.0
C_quant: 1000000.0
add_to_tracklet: null
alpha: 0.1
circuit_width: 9
class_weight:
  0: 1.0
  1: 1.0
classical: false
data_scaler: global
division: new_phi
gamma: 1
interaction: YY
load_model: false
model_file: /unix/atlastracking/marcinj/QuantumKernelEstimation/sliced_detector_analysis/saved_classifiers/scaled_inner_triplets/classical/model_from_class_opt_triplet_tr_40_reg_4.sav
num_test: 15
num_train: 20
pair_mapping: 1
region_id: '4'
single_mapping: 1
tracklet_dataset: triplet
