C_class: 1000000.0
C_quant: 1000000.0
add_to_tracklet: null
alpha: 0.1
circuit_width: 9
class_weight:
  0: 1.0
  1: 1.0
classical: true
data_scaler: inner_global
division: new_phi
gamma: 1
interaction: YY
load_model: true
model_file: /unix/atlastracking/marcinj/QuantumKernelEstimation/sliced_detector_analysis/saved_classifiers/scaled_inner_triplets/classical/model_from_scaled_class_opt_inner_triplet_tr_220_reg_0.sav
num_test: 60
num_train: 220
pair_mapping: 1
region_id: '0'
single_mapping: 1
tracklet_dataset: inner_triplet
